/**
 * List of actions authorized via roles. See Authorizations module.
 * Ultimately, this will be combined into the Authorization Roles enum.
 */
export enum AuthorizedActionsE {
  ADDRESS_CHANGE_FILING,
  ADMIN_DISSOLUTION_FILING,
  AGM_EXTENSION_FILING,
  AGM_CHG_LOCATION_FILING,
  ALTERATION_FILING,
  AMALGAMATION_FILING,
  ANNUAL_REPORT_FILING,
  CONSENT_AMALGAMATION_OUT_FILING,
  CONSENT_CONTINUATION_OUT_FILING,
  CORRECTION_FILING,
  COURT_ORDER_FILING,
  DETAIL_COMMENTS,
  DIRECTOR_CHANGE_FILING,
  DOCUMENT_RECORDS,
  FIRM_CHANGE_FILING,
  FIRM_CONVERSION_FILING,
  NO_CONTACT_INFO,
  NOTICE_WITHDRAWAL_FILING,
  REGISTRATION_FILING,
  RESTORATION_REINSTATEMENT_FILING,
  SPECIAL_RESOLUTION_FILING,
  STAFF_BREADCRUMBS,
  STAFF_COMMENTS,
  STAFF_FILINGS,
  TRANSITION_FILING,
  VOLUNTARY_DISSOLUTION_FILING
}
