/**
 * List of actions authorized via roles. See Authorizations module.
 * Ultimately, this will be combined into the Authorization Roles enum.
 */
export enum AuthorizedActionsE {
  ADDRESS_CHANGE_FILING,
  ADMIN_DISSOLUTION_FILING,
  AGM_EXTENSION_FILING,
  AGM_CHG_LOCATION_FILING,
  ALTERATION_FILING,
  AMALGAMATION_FILING,
  ANNUAL_REPORT_FILING,
  CONSENT_AMALGAMATION_OUT_FILING,
  CONSENT_CONTINUATION_OUT_FILING,
  CONVERSION_FILING,
  CORRECTION_FILING,
  COURT_ORDER_POA,
  DELAY_DISSOLUTION_FILING,
  DETAIL_COMMENTS,
  ENABLE_DOCUMENT_RECORDS,
  FIRM_CONVERSION_FILING,
  FREEZE_UNFREEZE_FILING,
  NO_CONTACT_INFO,
  RESTORATION_FILING,
  SPECIAL_RESOLUTION_FILING,
  STAFF_BREADCRUMBS,
  STAFF_COMMENTS,
  STAFF_FILING,
  VOLUNTARY_DISSOLUTION_FILING
}
