export enum FileUploadErrorE {
  MAX_SIZE_EXCEEDED = 'MAX_SIZE_EXCEEDED',
  INVALID_TYPE = 'INVALID_TYPE',
  ENCRYPTED = 'ENCRYPTED',
  LOCKED = 'LOCKED',
  INVALID_PAGE_SIZE = 'INVALID_PAGE_SIZE',
  UPLOAD_FAILED = 'UPLOAD_FAILED'
}
