export enum TodoContentE {
  PENDING = 'PENDING',
  ERROR = 'ERROR',
  PAID = 'PAID',
  CHANGE_REQUESTED = 'CHANGE_REQUESTED',
  ALTERING_TO_BEN = 'ALTERING_TO_BEN',
  APPROVED_CONTINUATION_IN = 'ARRPOVED_CONTINUATION_IN',
}
