export enum TodoExpansionContentE {
  AFFILIATION_INVITATION = 'AFFILIATION_INVITATION',
  DRAFT_PAYMENT_INCOMPLETE = 'DRAFT_PAYMENT_INCOMPLETE',
  CONVERSION = 'CONVERSION',
  DRAFT_CORRECTION = 'DRAFT_CORRECTION',
  CORRECTION = 'CORRECTION',
  DRAFT_WITH_NR = 'DRAFT_WITH_NR',
  PENDING_PAYMENT_ONLINE = 'PENDING_PAYMENT_ONLINE',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CHANGE_REQUESTED = 'CHANGE_REQUESTED',
  PAYMENT_ERROR = 'PAYMENT_ERROR',
  PAID = 'PAID'
}
