name: Business Dash CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  bus-dash-ui-cd:
    permissions:
      contents: "write"
      id-token: "write"
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-cd.yaml@main
    with:
      target: ${{ inputs.environment }}
      node_version: 20
      app_name: "business-dashboard-ui"
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
